version: '2'
services:
  api:
    image: sqwak/api
    command: supervisord -c ./supervisord.conf
    ports:
      - "8080:8080"

  nginx:
    image: sqwak/nginx
    links:
      - api:api
    ports:
      - "80:80"
      - "443:443"
  db:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
