version: '2'
services:
  frontend:
    image: sqwak/frontend
    ports:
      - "8082:3000"
    command: npm start
    environment:
      - REACT_APP_API_URL=localhost:8080

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"

  nginx:
    image: sqwak/nginx
    links:
      - frontend:frontend
    ports:
      - "80:80"
      - "443:443"
