version: '2'
services:
  web:
    build: ./web
    volumes:
      - ./web/app:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build: ./nginx

  feature_extractor:
    build: ./feature_extractor
    volumes: 
      - ./feature_extractor:/usr/src/app
    ports:
      - '50051:50051'
    command: python greeter_server.py