version: '2'
services:
  api:
    build: ./api
    volumes:
      - ./api/app:/usr/src/app
      - ./protos:/usr/src/app/protos
      - /usr/src/app/node_modules

  web:
    build: ./web
    volumes:
      - ./web/app:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build: ./nginx

  mongo:
    logging:
      driver: "none"

  feature_extractor:
    build: ./feature_extractor
    volumes: 
      - ./feature_extractor/app:/usr/src/app
      - ./protos:/usr/src/app/protos
    command: supervisord -c ./supervisord.conf
    ports:
      - "9001:9001"

  model_manager:
    build: ./model_manager
    volumes: 
      - ./model_manager/app:/usr/src/app
      - ./protos:/usr/src/app/protos
    command: supervisord -c ./supervisord.conf