version: '2'
services:
  api:
    image: sqwak/api
    command: python run.py
    ports:
      - "5000:5000"
      
  nginx:
    image: sqwak/nginx
    links:
      - api:api
    ports:
      - "80:80"
      - "443:443"