version: '2'
services:
  web:
    build: ./web
    volumes:
      - ./web/app:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build: ./nginx

  feature_extractor:
    build: ./feature_extractor
    volumes: 
      - ./feature_extractor/app:/usr/src/app
    command: python greeter_server.py

  model_manager:
    build: ./model_manager
    volumes: 
      - ./model_manager:/usr/src/app
    command: python greeter_server.py