version: '2'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build: ./nginx
  
  feature_extractor:
    build: ./feature_extractor
    volumes: 
      - ./feature_extractor:/usr/src/app
    command: python greeter_server.py
    ports:
      - '50051:50051'
