version: '2'
services:
  web:
    image: sqwak/web
    ports:
      - "3000:3000"
    command: npm start

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"

  nginx:
    image: sqwak/nginx
    links:
      - web:web
    ports:
      - "80:80"
      - "443:443"

  feature_extractor:
    image: sqwak/feature_extractor
    ports:
      - '50051:50051'
    command: python greeter_server.py