"""empty message

Revision ID: 3c1b7d905bdd
Revises: 
Create Date: 2017-02-21 08:32:18.322610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1b7d905bdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_app', sa.Column('last_published', sa.DateTime(), nullable=True))
    op.drop_column('ml_app', 'is_published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_app', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ml_app', 'last_published')
    # ### end Alembic commands ###
