"""empty message

Revision ID: 75680b28c5ef
Revises: 
Create Date: 2017-02-18 05:27:02.315761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75680b28c5ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_app', sa.Column('working_model_dirty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_app', 'working_model_dirty')
    # ### end Alembic commands ###
